#!/usr/bin/env sh

csp="default-src 'self';"
csp="$csp script-src 'self' https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/ https://analytics.lionskins.co/;"
csp="$csp style-src 'self' 'unsafe-inline' https:;"
csp="$csp img-src 'self' data: https:;"
csp="$csp frame-src https://www.google.com/recaptcha/;"
csp="$csp font-src 'self' data: https:;"
csp="$csp connect-src 'self' https://api.lionskins.co/ https://sentry.io/api/"
meta="<meta http-equiv=\"Content-Security-Policy\" content=\"\">"
new_meta="<meta http-equiv=\"Content-Security-Policy\" content=\"$csp\">";
sed -i "s#$meta#$new_meta#g" build/index.html