repos:
  - repo: https://github.com/Woile/commitizen
    rev: v2.24.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.2
    hooks:
      - id: prettier
        stages: [commit]
  - repo: https://github.com/gitguardian/ggshield
    rev: v1.11.0
    hooks:
      - id: ggshield
        language_version: python3
        stages: [commit]
