# Generated by Django 4.0.4 on 2022-04-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("csgo", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="skin",
            options={
                "ordering": [
                    "-type",
                    "weapon",
                    "group_slug",
                    "souvenir",
                    "stat_trak",
                    "quality",
                ]
            },
        ),
        migrations.AlterField(
            model_name="price",
            name="provider",
            field=models.CharField(
                choices=[
                    ("steam", "Steam"),
                    ("bitskins", "BitSkins"),
                    ("csmoney", "CSMoney"),
                    ("skinbaron", "SkinBaron"),
                    ("skinport", "Skinport"),
                    ("csgopshop", "csgoshop"),
                    ("lootbear", "Lootbear"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="skin",
            name="object_id",
            field=models.CharField(db_index=True, max_length=24, null=True),
        ),
        migrations.AddConstraint(
            model_name="skin",
            constraint=models.UniqueConstraint(
                fields=("market_hash_name",), name="unique_market_hash_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="skin",
            constraint=models.UniqueConstraint(
                condition=models.Q(("object_id__isnull", False)),
                fields=("object_id",),
                name="unique_object_id",
            ),
        ),
    ]
