# Generated by Django 4.0.4 on 2022-04-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("csgo", "0002_alter_skin_options_alter_price_provider_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skin",
            name="description",
            field=models.JSONField(default=dict),
        ),
    ]
