"""empty message

Revision ID: 167dde90887e
Revises: 94f7332b1b15
Create Date: 2018-08-21 17:14:01.155182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '167dde90887e'
down_revision = '94f7332b1b15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('COMMIT')  # the following command cannot run inside a transaction
    op.execute('ALTER TYPE type_csgo_weapons ADD value \'mp5_sd\' after \'mp7\';')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DELETE FROM pg_enum WHERE enumlabel = \'mp5_sd\' '
               'AND enumtypid = ('
               'SELECT oid FROM pg_type WHERE typname = \'type_csgo_weapons\''
               ')')
    # ### end Alembic commands ###
