"""empty message

Revision ID: 94f7332b1b15
Revises: 
Create Date: 2018-08-03 09:56:12.820705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94f7332b1b15'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=127), nullable=True),
    sa.Column('email', sa.String(length=127), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_creation_date'), 'contact', ['creation_date'], unique=False)
    op.create_table('csgo_weapons',
    sa.Column('id', sa.Enum('glock_18', 'usp_s', 'p2000', 'p250', 'cz75_auto', 'five_seven', 'tec_9', 'dual_berettas', 'desert_eagle', 'r8_revolver', 'sawed_off', 'mag_7', 'nova', 'xm1014', 'm249', 'negev', 'mac_10', 'mp9', 'pp_bizon', 'mp7', 'ump_45', 'p90', 'galil_ar', 'famas', 'ak_47', 'm4a4', 'm4a1_s', 'sg_553', 'aug', 'g3sg1', 'scar_20', 'ssg_08', 'awp', 'bayonet', 'bowie_knife', 'butterfly_knife', 'falchion_knife', 'flip_knife', 'gut_knife', 'huntsman_knife', 'karambit', 'm9_bayonet', 'navaja_knife', 'shadow_daggers', 'stiletto_knife', 'talon_knife', 'ursus_knife', name='type_csgo_weapons'), nullable=False),
    sa.Column('category', sa.Enum('pistols', 'heavy', 'smgs', 'rifles', 'knives', name='type_csgo_categories'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_csgo_weapons_category'), 'csgo_weapons', ['category'], unique=False)
    op.create_table('providers',
    sa.Column('id', sa.Enum('steam', 'bitskins', 'csgoshop', 'lootbear', name='type_providers'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skins',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('app', sa.Enum('csgo', name='type_apps'), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=127), nullable=False),
    sa.Column('image_url', sa.String(length=511), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skins_app'), 'skins', ['app'], unique=False)
    op.create_index(op.f('ix_skins_name'), 'skins', ['name'], unique=False)
    op.create_index(op.f('ix_skins_slug'), 'skins', ['slug'], unique=False)
    op.create_table('csgo_skins',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('weapon_id', sa.Enum('glock_18', 'usp_s', 'p2000', 'p250', 'cz75_auto', 'five_seven', 'tec_9', 'dual_berettas', 'desert_eagle', 'r8_revolver', 'sawed_off', 'mag_7', 'nova', 'xm1014', 'm249', 'negev', 'mac_10', 'mp9', 'pp_bizon', 'mp7', 'ump_45', 'p90', 'galil_ar', 'famas', 'ak_47', 'm4a4', 'm4a1_s', 'sg_553', 'aug', 'g3sg1', 'scar_20', 'ssg_08', 'awp', 'bayonet', 'bowie_knife', 'butterfly_knife', 'falchion_knife', 'flip_knife', 'gut_knife', 'huntsman_knife', 'karambit', 'm9_bayonet', 'navaja_knife', 'shadow_daggers', 'stiletto_knife', 'talon_knife', 'ursus_knife', name='type_csgo_weapons'), nullable=True),
    sa.Column('stat_trak', sa.Boolean(), nullable=True),
    sa.Column('souvenir', sa.Boolean(), nullable=True),
    sa.Column('quality', sa.Enum('factory_new', 'minimal_wear', 'field_tested', 'well_worn', 'battle_scarred', name='type_csgo_qualities'), nullable=True),
    sa.Column('rarity', sa.Enum('consumer_grade', 'industrial_grade', 'mil_spec', 'restricted', 'classified', 'covert', 'contraband', name='type_csgo_rarities'), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['skins.id'], ),
    sa.ForeignKeyConstraint(['weapon_id'], ['csgo_weapons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_csgo_skins_quality'), 'csgo_skins', ['quality'], unique=False)
    op.create_index(op.f('ix_csgo_skins_rarity'), 'csgo_skins', ['rarity'], unique=False)
    op.create_index(op.f('ix_csgo_skins_souvenir'), 'csgo_skins', ['souvenir'], unique=False)
    op.create_index(op.f('ix_csgo_skins_stat_trak'), 'csgo_skins', ['stat_trak'], unique=False)
    op.create_table('prices',
    sa.Column('skin_id', sa.String(length=36), nullable=False),
    sa.Column('provider_id', sa.Enum('steam', 'bitskins', 'csgoshop', 'lootbear', name='type_providers'), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['skin_id'], ['skins.id'], ),
    sa.PrimaryKeyConstraint('skin_id', 'provider_id')
    )
    op.create_index(op.f('ix_prices_price'), 'prices', ['price'], unique=False)
    op.create_table('redirects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('skin_id', sa.String(length=36), nullable=False),
    sa.Column('provider_id', sa.Enum('steam', 'bitskins', 'csgoshop', 'lootbear', name='type_providers'), nullable=False),
    sa.Column('tracker', sa.String(length=127), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['skin_id'], ['skins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_redirects_creation_date'), 'redirects', ['creation_date'], unique=False)
    op.create_index(op.f('ix_redirects_tracker'), 'redirects', ['tracker'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_redirects_tracker'), table_name='redirects')
    op.drop_index(op.f('ix_redirects_creation_date'), table_name='redirects')
    op.drop_table('redirects')
    op.drop_index(op.f('ix_prices_price'), table_name='prices')
    op.drop_table('prices')
    op.drop_index(op.f('ix_csgo_skins_stat_trak'), table_name='csgo_skins')
    op.drop_index(op.f('ix_csgo_skins_souvenir'), table_name='csgo_skins')
    op.drop_index(op.f('ix_csgo_skins_rarity'), table_name='csgo_skins')
    op.drop_index(op.f('ix_csgo_skins_quality'), table_name='csgo_skins')
    op.drop_table('csgo_skins')
    op.drop_index(op.f('ix_skins_slug'), table_name='skins')
    op.drop_index(op.f('ix_skins_name'), table_name='skins')
    op.drop_index(op.f('ix_skins_app'), table_name='skins')
    op.drop_table('skins')
    op.drop_table('providers')
    op.drop_index(op.f('ix_csgo_weapons_category'), table_name='csgo_weapons')
    op.drop_table('csgo_weapons')
    op.drop_index(op.f('ix_contact_creation_date'), table_name='contact')
    op.drop_table('contact')
    # ### end Alembic commands ###
