export const SET_CURRENCY = 'SET_CURRENCY'
export const SET_USER = 'SET_USER'
export const UNSET_USER = 'UNSET_USER'
export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN'
export const SET_REFRESH_TOKEN = 'SET_REFRESH_TOKEN'

export const CSGO_LOAD_SKINS = 'CSGO_LOAD_SKINS'
export const CSGO_RESET_SKINS = 'CSGO_RESET_SKINS'
export const CSGO_SET_FILTERS = 'CSGO_SET_FILTERS'
export const CSGO_SET_SKINS = 'CSGO_SET_SKINS'

export const TOGGLE_LOGIN_MODAL = 'TOGGLE_LOGIN_MODAL'
export const TOGGLE_SETTINGS_MODAL = 'TOGGLE_SETTINGS_MODAL'
export const TOGGLE_SIGNUP_MODAL = 'TOGGLE_SIGNUP_MODAL'
