# Generated by Django 4.0.4 on 2022-04-24 19:31

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_redirect_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProTeam",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("rank", models.PositiveSmallIntegerField(null=True)),
                ("liquipedia_id", models.CharField(max_length=128, null=True)),
                (
                    "creation_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "update_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="redirect",
            name="provider",
            field=models.CharField(
                choices=[
                    ("steam", "Steam"),
                    ("bitskins", "BitSkins"),
                    ("csmoney", "CSMoney"),
                    ("skinbaron", "SkinBaron"),
                    ("skinport", "Skinport"),
                    ("csgopshop", "csgoshop"),
                    ("lootbear", "Lootbear"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="ProPlayer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("nickname", models.CharField(max_length=128)),
                ("role", models.CharField(max_length=64)),
                ("slug", models.SlugField(max_length=128)),
                ("country_code", models.CharField(max_length=2, null=True)),
                (
                    "creation_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "update_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "team",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="players",
                        to="users.proteam",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
